name: PHP Composer Workflow

on:
  push:
    branches:
      - main  # Ganti dengan branch yang sesuai
  pull_request:
    branches:
      - main  # Ganti dengan branch yang sesuai
  # Atur event lain yang sesuai dengan kebutuhan Anda

jobs:
  build:
    runs-on: ubuntu-latest  # Gunakan image sesuai kebutuhan (ubuntu, windows, macos)
    
    steps:
    - uses: actions/checkout@v2  # Checkout kode dari repository
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2  # Setup PHP
      with:
        php-version: '8.0'  # Ganti dengan versi PHP yang Anda butuhkan
    
    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"
    
    - name: Validate Composer
      run: |
        ls  # Memastikan bahwa kita berada di direktori yang benar
        composer validate --no-check-all --ansi --no-interaction
    
    # Tambahkan langkah-langkah lain yang diperlukan, misalnya menjalankan tes PHP, dll.
    
